FROM nginxinc/nginx-unprivileged:stable-alpine
RUN echo '<html><body style="background-color:green;"><h1>Green Server</h1></body></html>' > /usr/share/nginx/html/index.html
RUN mkdir /var/cache/nginx/client_temp

